package com.gms.pos;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Announcement generated by hbm2java
 */
public class Announcement implements java.io.Serializable {

	private Long bannouncementId;
	private String vannouncementTitle;
	private String vannouncementDetails;
	private Date dannouncementTime;

	public Announcement() {
	}

	public Announcement(String vannouncementTitle, String vannouncementDetails, Date dannouncementTime) {
		this.vannouncementTitle = vannouncementTitle;
		this.vannouncementDetails = vannouncementDetails;
		this.dannouncementTime = dannouncementTime;
	}

	public Long getBannouncementId() {
		return this.bannouncementId;
	}

	public void setBannouncementId(Long bannouncementId) {
		this.bannouncementId = bannouncementId;
	}

	public String getVannouncementTitle() {
		return this.vannouncementTitle;
	}

	public void setVannouncementTitle(String vannouncementTitle) {
		this.vannouncementTitle = vannouncementTitle;
	}

	public String getVannouncementDetails() {
		return this.vannouncementDetails;
	}

	public void setVannouncementDetails(String vannouncementDetails) {
		this.vannouncementDetails = vannouncementDetails;
	}

	public Date getDannouncementTime() {
		return this.dannouncementTime;
	}

	public void setDannouncementTime(Date dannouncementTime) {
		this.dannouncementTime = dannouncementTime;
	}

}
