package com.gms.pos;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competitioncomment generated by hbm2java
 */
public class Competitioncomment implements java.io.Serializable {

	private Long bcommentId;
	private Competition competition;
	private String vcommentDetails;
	private Date dcommentTime;
	private Set competitionreplies = new HashSet(0);

	public Competitioncomment() {
	}

	public Competitioncomment(Competition competition, String vcommentDetails, Date dcommentTime,
			Set competitionreplies) {
		this.competition = competition;
		this.vcommentDetails = vcommentDetails;
		this.dcommentTime = dcommentTime;
		this.competitionreplies = competitionreplies;
	}

	public Long getBcommentId() {
		return this.bcommentId;
	}

	public void setBcommentId(Long bcommentId) {
		this.bcommentId = bcommentId;
	}

	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public String getVcommentDetails() {
		return this.vcommentDetails;
	}

	public void setVcommentDetails(String vcommentDetails) {
		this.vcommentDetails = vcommentDetails;
	}

	public Date getDcommentTime() {
		return this.dcommentTime;
	}

	public void setDcommentTime(Date dcommentTime) {
		this.dcommentTime = dcommentTime;
	}

	public Set getCompetitionreplies() {
		return this.competitionreplies;
	}

	public void setCompetitionreplies(Set competitionreplies) {
		this.competitionreplies = competitionreplies;
	}

}
