package com.gms.pos;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Equipment generated by hbm2java
 */
public class Equipment implements java.io.Serializable {

	private int iequipmentNo;
	private String vequipmentName;
	private String vkind;
	private Integer icompensate;
	private Integer iifrepair;
	private Integer irepair;
	private Set equipmentrents = new HashSet(0);
	private Set equitmentsuses = new HashSet(0);

	public Equipment() {
	}

	public Equipment(int iequipmentNo) {
		this.iequipmentNo = iequipmentNo;
	}

	public Equipment(int iequipmentNo, String vequipmentName, String vkind, Integer icompensate, Integer iifrepair,
			Integer irepair, Set equipmentrents, Set equitmentsuses) {
		this.iequipmentNo = iequipmentNo;
		this.vequipmentName = vequipmentName;
		this.vkind = vkind;
		this.icompensate = icompensate;
		this.iifrepair = iifrepair;
		this.irepair = irepair;
		this.equipmentrents = equipmentrents;
		this.equitmentsuses = equitmentsuses;
	}

	public int getIequipmentNo() {
		return this.iequipmentNo;
	}

	public void setIequipmentNo(int iequipmentNo) {
		this.iequipmentNo = iequipmentNo;
	}

	public String getVequipmentName() {
		return this.vequipmentName;
	}

	public void setVequipmentName(String vequipmentName) {
		this.vequipmentName = vequipmentName;
	}

	public String getVkind() {
		return this.vkind;
	}

	public void setVkind(String vkind) {
		this.vkind = vkind;
	}

	public Integer getIcompensate() {
		return this.icompensate;
	}

	public void setIcompensate(Integer icompensate) {
		this.icompensate = icompensate;
	}

	public Integer getIifrepair() {
		return this.iifrepair;
	}

	public void setIifrepair(Integer iifrepair) {
		this.iifrepair = iifrepair;
	}

	public Integer getIrepair() {
		return this.irepair;
	}

	public void setIrepair(Integer irepair) {
		this.irepair = irepair;
	}

	public Set getEquipmentrents() {
		return this.equipmentrents;
	}

	public void setEquipmentrents(Set equipmentrents) {
		this.equipmentrents = equipmentrents;
	}

	public Set getEquitmentsuses() {
		return this.equitmentsuses;
	}

	public void setEquitmentsuses(Set equitmentsuses) {
		this.equitmentsuses = equitmentsuses;
	}

}
