package com.gms.pos;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Roleinfo generated by hbm2java
 */
public class Roleinfo implements java.io.Serializable {

	private Integer iroleId;
	private String vroleName;
	private Set userinfos = new HashSet(0);

	public Roleinfo() {
	}

	public Roleinfo(String vroleName) {
		this.vroleName = vroleName;
	}

	public Roleinfo(String vroleName, Set userinfos) {
		this.vroleName = vroleName;
		this.userinfos = userinfos;
	}

	public Integer getIroleId() {
		return this.iroleId;
	}

	public void setIroleId(Integer iroleId) {
		this.iroleId = iroleId;
	}

	public String getVroleName() {
		return this.vroleName;
	}

	public void setVroleName(String vroleName) {
		this.vroleName = vroleName;
	}

	public Set getUserinfos() {
		return this.userinfos;
	}

	public void setUserinfos(Set userinfos) {
		this.userinfos = userinfos;
	}

}
