package com.gms.pos;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

/**
 * Spacesuse generated by hbm2java
 */
public class Spacesuse implements java.io.Serializable {

	private Long id;
	private Competition competition;
	private Fieldinfo fieldinfo;

	public Spacesuse() {
	}

	public Spacesuse(Competition competition, Fieldinfo fieldinfo) {
		this.competition = competition;
		this.fieldinfo = fieldinfo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public Fieldinfo getFieldinfo() {
		return this.fieldinfo;
	}

	public void setFieldinfo(Fieldinfo fieldinfo) {
		this.fieldinfo = fieldinfo;
	}

}
