package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
public class Competition implements java.io.Serializable {

	private Long bcompetitionId;
	private Competitiontype competitiontype;
	private Userinfo userinfo;
	private Date dapplyDate;
	private String vmainUnit;
	private String vcompetitionDetails;
	private String vcompetitionState;
	private String vunitAddress;
	private String vlinkMan;
	private String vphoneNumber;
	private Date dcompetitionDate;
	private Set spacesuses = new HashSet(0);
	private Set competitioncomments = new HashSet(0);
	private Competitionresult competitionresult;
	private Set equitmentsuses = new HashSet(0);
	private Competitioncost competitioncost;

	public Competition() {
	}

	public Competition(Competitiontype competitiontype, Userinfo userinfo, Date dapplyDate, String vmainUnit,
			String vcompetitionDetails, String vcompetitionState, String vunitAddress, String vlinkMan,
			String vphoneNumber, Date dcompetitionDate, Set spacesuses, Set competitioncomments,
			Competitionresult competitionresult, Set equitmentsuses, Competitioncost competitioncost) {
		this.competitiontype = competitiontype;
		this.userinfo = userinfo;
		this.dapplyDate = dapplyDate;
		this.vmainUnit = vmainUnit;
		this.vcompetitionDetails = vcompetitionDetails;
		this.vcompetitionState = vcompetitionState;
		this.vunitAddress = vunitAddress;
		this.vlinkMan = vlinkMan;
		this.vphoneNumber = vphoneNumber;
		this.dcompetitionDate = dcompetitionDate;
		this.spacesuses = spacesuses;
		this.competitioncomments = competitioncomments;
		this.competitionresult = competitionresult;
		this.equitmentsuses = equitmentsuses;
		this.competitioncost = competitioncost;
	}

	public Long getBcompetitionId() {
		return this.bcompetitionId;
	}

	public void setBcompetitionId(Long bcompetitionId) {
		this.bcompetitionId = bcompetitionId;
	}

	public Competitiontype getCompetitiontype() {
		return this.competitiontype;
	}

	public void setCompetitiontype(Competitiontype competitiontype) {
		this.competitiontype = competitiontype;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Date getDapplyDate() {
		return this.dapplyDate;
	}

	public void setDapplyDate(Date dapplyDate) {
		this.dapplyDate = dapplyDate;
	}

	public String getVmainUnit() {
		return this.vmainUnit;
	}

	public void setVmainUnit(String vmainUnit) {
		this.vmainUnit = vmainUnit;
	}

	public String getVcompetitionDetails() {
		return this.vcompetitionDetails;
	}

	public void setVcompetitionDetails(String vcompetitionDetails) {
		this.vcompetitionDetails = vcompetitionDetails;
	}

	public String getVcompetitionState() {
		return this.vcompetitionState;
	}

	public void setVcompetitionState(String vcompetitionState) {
		this.vcompetitionState = vcompetitionState;
	}

	public String getVunitAddress() {
		return this.vunitAddress;
	}

	public void setVunitAddress(String vunitAddress) {
		this.vunitAddress = vunitAddress;
	}

	public String getVlinkMan() {
		return this.vlinkMan;
	}

	public void setVlinkMan(String vlinkMan) {
		this.vlinkMan = vlinkMan;
	}

	public String getVphoneNumber() {
		return this.vphoneNumber;
	}

	public void setVphoneNumber(String vphoneNumber) {
		this.vphoneNumber = vphoneNumber;
	}

	public Date getDcompetitionDate() {
		return this.dcompetitionDate;
	}

	public void setDcompetitionDate(Date dcompetitionDate) {
		this.dcompetitionDate = dcompetitionDate;
	}

	public Set getSpacesuses() {
		return this.spacesuses;
	}

	public void setSpacesuses(Set spacesuses) {
		this.spacesuses = spacesuses;
	}

	public Set getCompetitioncomments() {
		return this.competitioncomments;
	}

	public void setCompetitioncomments(Set competitioncomments) {
		this.competitioncomments = competitioncomments;
	}

	public Competitionresult getCompetitionresult() {
		return this.competitionresult;
	}

	public void setCompetitionresult(Competitionresult competitionresult) {
		this.competitionresult = competitionresult;
	}

	public Set getEquitmentsuses() {
		return this.equitmentsuses;
	}

	public void setEquitmentsuses(Set equitmentsuses) {
		this.equitmentsuses = equitmentsuses;
	}

	public Competitioncost getCompetitioncost() {
		return this.competitioncost;
	}

	public void setCompetitioncost(Competitioncost competitioncost) {
		this.competitioncost = competitioncost;
	}

}
