package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

/**
 * Competitionresult generated by hbm2java
 */
public class Competitionresult implements java.io.Serializable {

	private long bcompetitionResultId;
	private Competition competition;
	private String vcompetitorUnit;
	private Integer iscores;

	public Competitionresult() {
	}

	public Competitionresult(long bcompetitionResultId, Competition competition, String vcompetitorUnit) {
		this.bcompetitionResultId = bcompetitionResultId;
		this.competition = competition;
		this.vcompetitorUnit = vcompetitorUnit;
	}

	public Competitionresult(long bcompetitionResultId, Competition competition, String vcompetitorUnit,
			Integer iscores) {
		this.bcompetitionResultId = bcompetitionResultId;
		this.competition = competition;
		this.vcompetitorUnit = vcompetitorUnit;
		this.iscores = iscores;
	}

	public long getBcompetitionResultId() {
		return this.bcompetitionResultId;
	}

	public void setBcompetitionResultId(long bcompetitionResultId) {
		this.bcompetitionResultId = bcompetitionResultId;
	}

	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public String getVcompetitorUnit() {
		return this.vcompetitorUnit;
	}

	public void setVcompetitorUnit(String vcompetitorUnit) {
		this.vcompetitorUnit = vcompetitorUnit;
	}

	public Integer getIscores() {
		return this.iscores;
	}

	public void setIscores(Integer iscores) {
		this.iscores = iscores;
	}

}
