package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.sql.Timestamp;

/**
 * Competitionreply generated by hbm2java
 */
public class Competitionreply implements java.io.Serializable {

	private Long breplyId;
	private Competitioncomment competitioncomment;
	private String vreplyContents;
	private Timestamp dreplyTime=new Timestamp(new java.util.Date().getTime());

	public Competitionreply() {
	}

	public Competitionreply(Competitioncomment competitioncomment, String vreplyContents, Timestamp dreplyTime) {
		this.competitioncomment = competitioncomment;
		this.vreplyContents = vreplyContents;
		this.dreplyTime = dreplyTime;
	}

	public Long getBreplyId() {
		return this.breplyId;
	}

	public void setBreplyId(Long breplyId) {
		this.breplyId = breplyId;
	}

	public Competitioncomment getCompetitioncomment() {
		return this.competitioncomment;
	}

	public void setCompetitioncomment(Competitioncomment competitioncomment) {
		this.competitioncomment = competitioncomment;
	}

	public String getVreplyContents() {
		return this.vreplyContents;
	}

	public void setVreplyContents(String vreplyContents) {
		this.vreplyContents = vreplyContents;
	}

	public Timestamp getDreplyTime() {
		return this.dreplyTime;
	}

	public void setDreplyTime(Timestamp dreplyTime) {
		this.dreplyTime = dreplyTime;
	}

}
