package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Competitiontype generated by hbm2java
 */
public class Competitiontype implements java.io.Serializable {

	private Integer icompetitionType;
	private String vcompetitionName;

	public Competitiontype() {
	}

	public Competitiontype(String vcompetitionName) {
		this.vcompetitionName = vcompetitionName;
	}

	public Integer getIcompetitionType() {
		return this.icompetitionType;
	}

	public void setIcompetitionType(Integer icompetitionType) {
		this.icompetitionType = icompetitionType;
	}

	public String getVcompetitionName() {
		return this.vcompetitionName;
	}

	public void setVcompetitionName(String vcompetitionName) {
		this.vcompetitionName = vcompetitionName;
	}

}
