package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Equipmentrent generated by hbm2java
 */
public class Equipmentrent implements java.io.Serializable {

	private int irentNo;
	private Equipment equipment;
	private Userinfo userinfo;
	private Integer iquantity;
	private Integer irentPrice;
	private Date drentDate;
	private Date dreturnDate;
	private Integer itoFreturn;
	private Integer iauthId;
	private Integer iaccountId;

	public Equipmentrent() {
	}

	public Equipmentrent(int irentNo) {
		this.irentNo = irentNo;
	}

	public Equipmentrent(int irentNo, Equipment equipment, Userinfo userinfo, Integer iquantity, Integer irentPrice,
			Date drentDate, Date dreturnDate, Integer itoFreturn, Integer iauthId, Integer iaccountId) {
		this.irentNo = irentNo;
		this.equipment = equipment;
		this.userinfo = userinfo;
		this.iquantity = iquantity;
		this.irentPrice = irentPrice;
		this.drentDate = drentDate;
		this.dreturnDate = dreturnDate;
		this.itoFreturn = itoFreturn;
		this.iauthId = iauthId;
		this.iaccountId = iaccountId;
	}

	public int getIrentNo() {
		return this.irentNo;
	}

	public void setIrentNo(int irentNo) {
		this.irentNo = irentNo;
	}

	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Integer getIquantity() {
		return this.iquantity;
	}

	public void setIquantity(Integer iquantity) {
		this.iquantity = iquantity;
	}

	public Integer getIrentPrice() {
		return this.irentPrice;
	}

	public void setIrentPrice(Integer irentPrice) {
		this.irentPrice = irentPrice;
	}

	public Date getDrentDate() {
		return this.drentDate;
	}

	public void setDrentDate(Date drentDate) {
		this.drentDate = drentDate;
	}

	public Date getDreturnDate() {
		return this.dreturnDate;
	}

	public void setDreturnDate(Date dreturnDate) {
		this.dreturnDate = dreturnDate;
	}

	public Integer getItoFreturn() {
		return this.itoFreturn;
	}

	public void setItoFreturn(Integer itoFreturn) {
		this.itoFreturn = itoFreturn;
	}

	public Integer getIauthId() {
		return this.iauthId;
	}

	public void setIauthId(Integer iauthId) {
		this.iauthId = iauthId;
	}

	public Integer getIaccountId() {
		return this.iaccountId;
	}

	public void setIaccountId(Integer iaccountId) {
		this.iaccountId = iaccountId;
	}

}
