package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

/**
 * Equitmentsuse generated by hbm2java
 */
public class Equitmentsuse implements java.io.Serializable {

	private Long bequitmentUsingId;
	private Competition competition;
	private Equipment equipment;
	private Integer iequitmentNum;

	public Equitmentsuse() {
	}

	public Equitmentsuse(Equipment equipment) {
		this.equipment = equipment;
	}

	public Equitmentsuse(Competition competition, Equipment equipment, Integer iequitmentNum) {
		this.competition = competition;
		this.equipment = equipment;
		this.iequitmentNum = iequitmentNum;
	}

	public Long getBequitmentUsingId() {
		return this.bequitmentUsingId;
	}

	public void setBequitmentUsingId(Long bequitmentUsingId) {
		this.bequitmentUsingId = bequitmentUsingId;
	}

	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	public Integer getIequitmentNum() {
		return this.iequitmentNum;
	}

	public void setIequitmentNum(Integer iequitmentNum) {
		this.iequitmentNum = iequitmentNum;
	}

}
