package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Fieldinfo generated by hbm2java
 */
public class Fieldinfo implements java.io.Serializable {

	private long lfieldId;
	private String vfieldName;
	private String vlocation;
	private String vtype;
	private int isize;
	private boolean benableRent;
	private int ipeople;
	private int irentH;
	private Set spacesuses = new HashSet(0);
	private Set filedrentinfos = new HashSet(0);

	public Fieldinfo() {
	}

	public Fieldinfo(long lfieldId, String vfieldName, String vlocation, int isize, boolean benableRent, int ipeople,
			int irentH) {
		this.lfieldId = lfieldId;
		this.vfieldName = vfieldName;
		this.vlocation = vlocation;
		this.isize = isize;
		this.benableRent = benableRent;
		this.ipeople = ipeople;
		this.irentH = irentH;
	}

	public Fieldinfo(long lfieldId, String vfieldName, String vlocation, String vtype, int isize, boolean benableRent,
			int ipeople, int irentH, Set spacesuses, Set filedrentinfos) {
		this.lfieldId = lfieldId;
		this.vfieldName = vfieldName;
		this.vlocation = vlocation;
		this.vtype = vtype;
		this.isize = isize;
		this.benableRent = benableRent;
		this.ipeople = ipeople;
		this.irentH = irentH;
		this.spacesuses = spacesuses;
		this.filedrentinfos = filedrentinfos;
	}

	public long getLfieldId() {
		return this.lfieldId;
	}

	public void setLfieldId(long lfieldId) {
		this.lfieldId = lfieldId;
	}

	public String getVfieldName() {
		return this.vfieldName;
	}

	public void setVfieldName(String vfieldName) {
		this.vfieldName = vfieldName;
	}

	public String getVlocation() {
		return this.vlocation;
	}

	public void setVlocation(String vlocation) {
		this.vlocation = vlocation;
	}

	public String getVtype() {
		return this.vtype;
	}

	public void setVtype(String vtype) {
		this.vtype = vtype;
	}

	public int getIsize() {
		return this.isize;
	}

	public void setIsize(int isize) {
		this.isize = isize;
	}

	public boolean isBenableRent() {
		return this.benableRent;
	}

	public void setBenableRent(boolean benableRent) {
		this.benableRent = benableRent;
	}

	public int getIpeople() {
		return this.ipeople;
	}

	public void setIpeople(int ipeople) {
		this.ipeople = ipeople;
	}

	public int getIrentH() {
		return this.irentH;
	}

	public void setIrentH(int irentH) {
		this.irentH = irentH;
	}

	public Set getSpacesuses() {
		return this.spacesuses;
	}

	public void setSpacesuses(Set spacesuses) {
		this.spacesuses = spacesuses;
	}

	public Set getFiledrentinfos() {
		return this.filedrentinfos;
	}

	public void setFiledrentinfos(Set filedrentinfos) {
		this.filedrentinfos = filedrentinfos;
	}

}
