package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import org.apache.struts2.json.annotations.JSON;

/**
 * Fieldinfo generated by hbm2java
 */
public class Fieldinfo implements java.io.Serializable {

	private long fieldId;
	private String fieldName;
	private String location;
	private int size;
	//private boolean enableRent;
	private int people;
	private int rentH;
	// private Set spacesuses = new HashSet(0);
	private Set fieldrentinfos = new HashSet(0);
	private Fieldtype fieldtype;

	public long getFieldId() {
		return fieldId;
	}

	public void setFieldId(long fieldId) {
		this.fieldId = fieldId;
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@JSON(serialize=false)
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@JSON(serialize=false)
	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	@JSON(serialize=false)
	public int getPeople() {
		return people;
	}

	public void setPeople(int people) {
		this.people = people;
	}

	@JSON(serialize=false)
	public int getRentH() {
		return rentH;
	}

	public void setRentH(int rentH) {
		this.rentH = rentH;
	}

	@JSON(serialize=false)
	public Set getFieldrentinfos() {
		return fieldrentinfos;
	}

	public void setFieldrentinfos(Set fieldrentinfos) {
		this.fieldrentinfos = fieldrentinfos;
	}

	@JSON(serialize=false)
	public Fieldtype getFieldtype() {
		return fieldtype;
	}

	public void setFieldtype(Fieldtype fieldtype) {
		this.fieldtype = fieldtype;
	}

	@Override
	public String toString() {
		return "Fieldinfo [fieldId=" + fieldId + ", fieldName=" + fieldName + ", location=" + location + ", size="
				+ size + ", people=" + people + ", rentH=" + rentH + ", fieldrentinfos=" + fieldrentinfos
				+ ", fieldtype=" + fieldtype + "]";
	}

}
