package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Fieldinfo generated by hbm2java
 */
public class Fieldinfo implements java.io.Serializable {

	private long lfieldId;
	private String vfieldName;
	private String vlocation;
	private int isize;
	private boolean benableRent;
	private int ipeople;
	private int irentH;
	// private Set spacesuses = new HashSet(0); 场地就不关联赛事信息了
	private Set filedrentinfos = new HashSet(0);
	private Fieldtype fieldType;

	public long getLfieldId() {
		return lfieldId;
	}

	public void setLfieldId(long lfieldId) {
		this.lfieldId = lfieldId;
	}

	public String getVfieldName() {
		return vfieldName;
	}

	public void setVfieldName(String vfieldName) {
		this.vfieldName = vfieldName;
	}

	public String getVlocation() {
		return vlocation;
	}

	public void setVlocation(String vlocation) {
		this.vlocation = vlocation;
	}

	public int getIsize() {
		return isize;
	}

	public void setIsize(int isize) {
		this.isize = isize;
	}

	public boolean isBenableRent() {
		return benableRent;
	}

	public void setBenableRent(boolean benableRent) {
		this.benableRent = benableRent;
	}

	public int getIpeople() {
		return ipeople;
	}

	public void setIpeople(int ipeople) {
		this.ipeople = ipeople;
	}

	public int getIrentH() {
		return irentH;
	}

	public void setIrentH(int irentH) {
		this.irentH = irentH;
	}

	public Set getFiledrentinfos() {
		return filedrentinfos;
	}

	public void setFiledrentinfos(Set filedrentinfos) {
		this.filedrentinfos = filedrentinfos;
	}

	public Fieldtype getFieldType() {
		return fieldType;
	}

	public void setFieldType(Fieldtype fieldType) {
		this.fieldType = fieldType;
	}

}
