package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Filedrentinfo generated by hbm2java
 */
public class Fieldrentinfo implements java.io.Serializable {

	private long fieldrentId;
	private Fieldinfo fieldinfo;
	private Userinfo userinfo;
	private Date startTime;
	private Date endTime;
	private int rent;
	private Boolean status;

	public long getFieldrentId() {
		return fieldrentId;
	}

	public void setFieldrentId(long fieldrentId) {
		this.fieldrentId = fieldrentId;
	}

	public Fieldinfo getFieldinfo() {
		return fieldinfo;
	}

	public void setFieldinfo(Fieldinfo fieldinfo) {
		this.fieldinfo = fieldinfo;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public int getRent() {
		return rent;
	}

	public void setRent(int rent) {
		this.rent = rent;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
