package com.gms.po;
// Generated 2017-5-21 12:46:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.struts2.json.annotations.JSON;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer iuserId;
	private Roleinfo roleinfo;
	private String vuserName;
	private String vpassward;
	private String vrealName;
	private Integer ivstate;
	private String vtelephone;
	private String vemail;
	private Integer iidentifierType;
	private String videntifierCode;
	private String videntifierAddress;
	private Date dbirthday;
	private String vcollege;
	private String vaddress;
	private Set filedrentinfos = new HashSet(0);
	private Set competitions = new HashSet(0);
	private Set equipmentrents = new HashSet(0);

	public Userinfo() {
	}

	public Userinfo(Roleinfo roleinfo, String vuserName, String vpassward) {
		this.roleinfo = roleinfo;
		this.vuserName = vuserName;
		this.vpassward = vpassward;
	}

	public Userinfo(Roleinfo roleinfo, String vuserName, String vpassward, String vrealName, Integer ivstate,
			String vtelephone, String vemail, Integer iidentifierType, String videntifierCode,
			String videntifierAddress, Date dbirthday, String vcollege, String vaddress, Set filedrentinfos,
			Set competitions, Set equipmentrents) {
		this.roleinfo = roleinfo;
		this.vuserName = vuserName;
		this.vpassward = vpassward;
		this.vrealName = vrealName;
		this.ivstate = ivstate;
		this.vtelephone = vtelephone;
		this.vemail = vemail;
		this.iidentifierType = iidentifierType;
		this.videntifierCode = videntifierCode;
		this.videntifierAddress = videntifierAddress;
		this.dbirthday = dbirthday;
		this.vcollege = vcollege;
		this.vaddress = vaddress;
		this.filedrentinfos = filedrentinfos;
		this.competitions = competitions;
		this.equipmentrents = equipmentrents;
	}

	public Integer getIuserId() {
		return this.iuserId;
	}

	public void setIuserId(Integer iuserId) {
		this.iuserId = iuserId;
	}

	@JSON(serialize=false)
	public Roleinfo getRoleinfo() {
		return this.roleinfo;
	}

	public void setRoleinfo(Roleinfo roleinfo) {
		this.roleinfo = roleinfo;
	}

	public String getVuserName() {
		return this.vuserName;
	}

	public void setVuserName(String vuserName) {
		this.vuserName = vuserName;
	}

	@JSON(serialize=false)
	public String getVpassward() {
		return this.vpassward;
	}

	public void setVpassward(String vpassward) {
		this.vpassward = vpassward;
	}

	@JSON(serialize=false)
	public String getVrealName() {
		return this.vrealName;
	}

	public void setVrealName(String vrealName) {
		this.vrealName = vrealName;
	}

	@JSON(serialize=false)
	public Integer getIvstate() {
		return this.ivstate;
	}

	public void setIvstate(Integer ivstate) {
		this.ivstate = ivstate;
	}

	@JSON(serialize=false)
	public String getVtelephone() {
		return this.vtelephone;
	}

	public void setVtelephone(String vtelephone) {
		this.vtelephone = vtelephone;
	}

	@JSON(serialize=false)
	public String getVemail() {
		return this.vemail;
	}

	public void setVemail(String vemail) {
		this.vemail = vemail;
	}

	@JSON(serialize=false)
	public Integer getIidentifierType() {
		return this.iidentifierType;
	}

	public void setIidentifierType(Integer iidentifierType) {
		this.iidentifierType = iidentifierType;
	}

	@JSON(serialize=false)
	public String getVidentifierCode() {
		return this.videntifierCode;
	}

	public void setVidentifierCode(String videntifierCode) {
		this.videntifierCode = videntifierCode;
	}

	@JSON(serialize=false)
	public String getVidentifierAddress() {
		return this.videntifierAddress;
	}

	public void setVidentifierAddress(String videntifierAddress) {
		this.videntifierAddress = videntifierAddress;
	}

	@JSON(serialize=false)
	public Date getDbirthday() {
		return this.dbirthday;
	}

	public void setDbirthday(Date dbirthday) {
		this.dbirthday = dbirthday;
	}

	@JSON(serialize=false)
	public String getVcollege() {
		return this.vcollege;
	}

	public void setVcollege(String vcollege) {
		this.vcollege = vcollege;
	}

	@JSON(serialize=false)
	public String getVaddress() {
		return this.vaddress;
	}

	public void setVaddress(String vaddress) {
		this.vaddress = vaddress;
	}

	@JSON(serialize=false)
	public Set getFiledrentinfos() {
		return this.filedrentinfos;
	}

	public void setFiledrentinfos(Set filedrentinfos) {
		this.filedrentinfos = filedrentinfos;
	}

	@JSON(serialize=false)
	public Set getCompetitions() {
		return this.competitions;
	}

	public void setCompetitions(Set competitions) {
		this.competitions = competitions;
	}

	@JSON(serialize=false)
	public Set getEquipmentrents() {
		return this.equipmentrents;
	}

	public void setEquipmentrents(Set equipmentrents) {
		this.equipmentrents = equipmentrents;
	}

}
